source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'rake'
gem 'hoptoad_notifier'
gem 'authlogic'
source 'http://gemcutter.org'
gem 'acl9', :require => 'acl9'
source 'http://gemcutter.org'
gem 'factory_girl'
gem 'fastercsv'
gem 'prawn'
gem 'liquid'
gem 'validates_email_format_of'
gem 'spreadsheet'
gem 'money'
